# {{ ansible_managed }}
apiVersion: v1
baseDomain: {{ openshift_install_config.base_domain }}
compute:
- hyperthreading: Enabled
  name: worker
  replicas: {{ openshift_install_config.worker_replicas }}
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: {{ openshift_install_config.master_replicas }}
metadata:
  name: {{ openshift_install_config.name }}
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  # Uncomment this if installing to Bare metal, Libvirt, and oVirt target platforms
#  none: {}
  # Uncomment this if installing to vSphere target platform. Remove the commented lines if you are not
  # installing on vSphere.
  vsphere:
    vcenter: '{{ vsphere.vcenter_hostname }}'
    username: '{{ vsphere.vcenter_username  }}'
    password: '{{ vsphere.vcenter_password  }}'
    datacenter: '{{ vsphere.datacenter_name }}'
    defaultDatastore: '{{ vsphere.datastore_name }}'
fips: false
pullSecret: '{{ openshift_install_config.pull_secret }}'
sshKey: '{{ openshift_install_config.ssh_key }}'

# Routing outgoing traffic through a cluster-wide proxy.
# If your proxy certificate is signed by a certificate authority which RHCOS does not trust by default,
# you may also wish to add the CA's certificate to the additionalTrustBundle. If additionalTrustBundle
# and at least one proxy setting are configured, the cluster Proxy object will be configured with
# trustedCA referencing the additional trust bundle.
#proxy:
#  httpsProxy: https://username:password@proxy.example.com:123/
#  httpProxy: https://username:password@proxy.example.com:123/
#  noProxy: 123.example.com,10.88.0.0/16

# Certificate bundle that will be added to the nodes' trusted certificate store. This trust bundle may
# also be used when a proxy has been configured or when using a mirror registry.
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIEWTCCA0GgAwIBAgIJAIyOUxkTbrPWMA0GCSqGSIb3DQEBCwUAMIHCMQswCQYD
  VQQGEwJVUzELMAkGA1UECAwCTUQxFTATBgNVBAcMDE93aW5ncyBNaWxsczEVMBMG
  A1UECgwMUEFPU0lOIExPQ0FMMUEwPwYDVQQLDDhQQU9TSU4ICAgICAhJVBtbM34b
  WzN+G1szfhtbQxtbQxtbQxtbQxtbQwgICAgICAhQTwhBT1NJTjEVMBMGA1UEAwwM
  UEFPU0lOIExPQ0FMMR4wHAYJKoZIhvcNAQkBFg9mZW1pQHBhb3Npbi5jb20wHhcN
  MTgwOTEyMTYxNjE1WhcNMjMwOTExMTYxNjE1WjCBwjELMAkGA1UEBhMCVVMxCzAJ
  BgNVBAgMAk1EMRUwEwYDVQQHDAxPd2luZ3MgTWlsbHMxFTATBgNVBAoMDFBBT1NJ
  TiBMT0NBTDFBMD8GA1UECww4UEFPU0lOCAgICAgISVQbWzN+G1szfhtbM34bW0Mb
  W0MbW0MbW0MbW0MICAgICAgIUE8IQU9TSU4xFTATBgNVBAMMDFBBT1NJTiBMT0NB
  TDEeMBwGCSqGSIb3DQEJARYPZmVtaUBwYW9zaW4uY29tMIIBIjANBgkqhkiG9w0B
  AQEFAAOCAQ8AMIIBCgKCAQEA4RdnIWPoXjVj1ezNCj5JLsu///rSfzNbrO4z2UdE
  aZqd83dN0vfUW7Qp0rt+gsbojS6+d6Cy+KCI2/IJnXTfLO9N3f3mC9rFHujcA+PR
  m/ja4cDdWHEF7vwdpjWsNuAc451Rp3yq4qIAc2smlbs8eUJChIZU4+r5cudNT0RA
  YqzxuDeFyLIiYV3aBJtRUyadRhT9EUYOzu1KB/kPjjJJM5eqdKRtVTafw18UyyIX
  Ay6TLgnnd654o8+Ae2IjrxkE/6cuuQqX2aPYgyCUpDY6s3D0fzl4CL45IyLicb0D
  htvd6LIxBkVjJ9Ccm1LTkmkLSwN/1TFRPA+teJtaucWUYQIDAQABo1AwTjAdBgNV
  HQ4EFgQU5VKGr8wK7WdMwgtkxfgwziNAgyUwHwYDVR0jBBgwFoAU5VKGr8wK7WdM
  wgtkxfgwziNAgyUwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAzE9h
  VAgbAKuqhuzVEI9joTIycbEs2QvykV+iC71paIkQjiDt8RRHWZeFf0prdqEy9ISF
  N5qLPfflu6HRkhO47Sw/SdySzUkA2RiEnURi54yqbI8xsYIN3MMyJnuZ+nd+tSEO
  6qU+Pej30RTWgBhfxeuJK+/RwHPE3WjXfoH0Ejl/PI8XJaYMS/APRaW/MLVve3A6
  onoHRb+HtFc52WfGuT6euwe/mW8tB9qmPyeDLTlAxyGcXdwW60/g87wsc79jJHtY
  7hsT9yzD/f6NoE013EJnbgkWDYVK0Udj7kvJUZHLbqWEzZIXYaj4LWWgGe+NBV6f
  yfVWdmJSiJVy7WClEA==
  -----END CERTIFICATE-----
#additionalTrustBundle: |
#  -----BEGIN CERTIFICATE-----
#  ...base-64-encoded, Certificate Authority cert...
#  -----END CERTIFICATE-----
#
#  -----BEGIN CERTIFICATE-----
#  ...base-64-encoded, Certificate Authority cert...
#  -----END CERTIFICATE-----

# Mirror registry.
# If your mirror(s) are signed by a certificate authority which RHCOS does not trust by default, you may
# also wish to configure an additional trust bundle.
#imageContentSources:
#- mirrors:
#  - 192.168.150.2:5001/openshift-release-dev/ocp4
#  source: quay.io/openshift-release-dev/ocp-release
#- mirrors:
#  - 192.168.150.2:5001/openshift-release-dev/ocp4
#  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
