# OpenShift Installer configuration
openshift_install_config:
  # Choose OpenShift distribution (either ocp or okd):
  # ocp = Red Hat OpenShift Container Platform, https://www.openshift.com/
  # okd = Community distribution of Kubernetes, https://www.okd.io/
  distribution: ocp
  # Version of OpenShift to be installed (OCP or OKD).
  # For available OCP versions, go to https://mirror.openshift.com/pub/openshift-v4/clients/ocp
  # For available OKD versions, go to https://github.com/openshift/okd/releases
  version: 4.9.15
  # Unique name of the OpenShift cluster which also becomes a part of cluster's FQDN.
  name: ocp4-c01
  # Base domain which is appended to the cluster's name to form a cluster FQDN.
  #
  dns_host_domain: rnd.paosin.local
  #
  base_domain: paosin.local
  # FQDN of the OpenShift cluster. It must be in the format <name>.<base_domain>
  cluster_domain: ocp4-c01.paosin.local
  # Number of master nodes. Set this to 3 to achieve a highly-available control plane.
  master_replicas: 1
  # Number of worker nodes equals to the number of infra nodes + the number of app nodes.
  # Typical production installation will have 3 infra nodes. Regardless of how many
  # worker nodes you will deploy, you must set the value of the replicas parameter to 0.
  # This parameter controls the number of workers that the cluster creates and manages
  # for you, which are functions that the cluster does not perform when you use
  # user-provisioned infrastructure.
  worker_replicas: 0
  # This URL will be accessed by OpenShift nodes during the bootstrap in order
  # for them to download their ignition files. Make sure that this URL is reachable
  # from the OpenShift nodes. Note that this URL is only used for bare metal and
  # Libvirt PXE installations. You can leave it as is for other installation targets as
  # it won't be used.
  ignition_url_prefix: 'http://192.168.150.2:81/openshift-auto-upi/mycluster'
  # Configure OpenShift hosts using static IPs as opposed to using DHCP.
  # This feature is currently supported for bare metal, libvirt_pxe, oVirt, and vSphere.
  # It is not supported for libvirt_fwcfg.
  # For bare metal and libvirt_pxe, the PXE menu config is modified to include the
  # static IP configuration.
  # For oVirt and vSphere, a boot ISO is created that includes a custom GRUB boot loader
  # configuration that includes the static IP configuration. This custom GRUB confguration
  # is used only during the first boot of the OpenShift hosts. Following boots will go
  # back to using the factory GRUB configuration.
  static_ips:
    # Must enable in order to use the static IP provisioning.
    enabled: True
    parameters:
      gateway: 10.10.10.1
      netmask: 255.255.255.0
      # On oVirt, the network interface name is most likely "enp1s0".
      interface: ens192
      # List of DNS servers
      nameservers:
        - 10.10.10.11
  # When you deploy the cluster, this public SSH key is added to the core user’s
  # ~/.ssh/authorized_keys list. You can use this key to SSH into the OpenShift nodes
  # as the user core. By default, local user's public SSH key is added.
  ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCs32qztsS6q891fuImhge6yG1yvmjTaxfJAWCluRBC1vGq5BRNr47mvwV2yP7QQpuKyVEWXuFrZVMshuskH2dQr6zIVPudS6aCopZtYwBZgaf4aKXh9WKco4ibBgqzUb22m2gCDCObFR4nBcIx604cxKFvdRbG+K6BRyrILTyTTJ7I99ju2yq3pGBjc1SndDGsDJcAya54tcvjlAhAeJvvEudXve7Mazu9+eP/EZPtaIX5XapoyqChH70SRJ0QHZFX1c6hgvbiMoYlU18XSSggledNawy+94GcywiQ2z2bLh48DOuf0xmaXEpgGfqsw0VUmR3JVWWg1DJHg8q1z8somlSbms3yIu3NyqgZbJwQu73k21kNJD+SCjC2+nNAp1ap7zxzzmOqLGObri10DgaagKn8paD6v9q4Lr6S82BfBaSEWccR/hDynUWg7bMmBqSjyg8iXJiYX/CLPsZezkApaHEMqQw83GkUSBhjbzhsPY+P7rSpFkm8+jo57cQ29M0= root@bastion.paosin.local'
  # This is a JSON formatted pull secret that you can obtain at
  # https://cloud.redhat.com when installing a new OpenShift cluster. There is a
  # button "Download pull secret" that downloads this pull secret for you.
  # The secret contains keys for downloading container images from several Red Hat
  # repositories like quay.io, registry.connect.redhat.com, registry.redhat.io and
  # also keys for authenticating against the cloud.openshift.com itself.
  pull_secret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29sdXdhZmVtaW9zaW5vd28xaWdwcTkzYjUwaXpiNjB6ajBjNnJ4YXBmc3g6VTI5M0ZUWDNRWjBXVEw3T1JCQlNTM0o5RUNTTzFSMUJaUVMzVjFISFRLNDJGUjlIOVBPMkdXN082UVZMOUpYRQ==","email":"oluwafemi.osinowo@outlook.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29sdXdhZmVtaW9zaW5vd28xaWdwcTkzYjUwaXpiNjB6ajBjNnJ4YXBmc3g6VTI5M0ZUWDNRWjBXVEw3T1JCQlNTM0o5RUNTTzFSMUJaUVMzVjFISFRLNDJGUjlIOVBPMkdXN082UVZMOUpYRQ==","email":"oluwafemi.osinowo@outlook.com"},"registry.connect.redhat.com":{"auth":"NTIzOTYwODd8dWhjLTFJR1BxOTNCNTBpWmI2MFpKMEM2cnhBcEZTeDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTFNVFk1TW1VMU1UUXhOMkkwTTJZME9XRXlOVE01WkRCaU5EQTFNRFkxTmlKOS5maGU1OXFaVjlTZmI0Q2kxQkRReG12U25WQzBpZC05YlJLSlV2UUpaczR0d0NkbEZuZng1c2ZRaFdkVDgzMnVsQmlWNFlqekJNM2J5MlBfM041M1hTTXhxS3FZQkNuakNWck9OZjhjSWdkTXh2V25oTVV5SzdrZVkwcU5iM3h1aU9YUjVvV3FjeWVoeVgwRzBqdUlya01NUTRTcnVtcHVkdmxockE1eWtvMzNfRzlpaU9YQklzVmY5TmxLb1NyRDNMOFZkNlByTHQxNFRGX3Y5bHJDWEs5NV9sY3dqNV9jVWpTaEFILTdoLXJvOG1kNlptWVBtMlVxeDFkNFNfN3hJWDItaUtXeUl6ZEJjN196OXVEUlRPRGFiLVgyOG81YmYtcjdfazFxOHk2eHE1dWhQV0tRbGFRakhyVU5tYll0LTFydzVNbFM5X3NBZ2YxMjk5YTFPZVlsWTFKVG1wdHhma0hjc2prdGUyZDRiQWdPeGhiYVpfRklIY1h6SjNndHpZOEpnYXFncnkyU2JsWUFRNHF3bkNYanlkYThDa2J0WC1YRzZILVdUUGo2SUJmZEhpbjRON1RqT0FrVEtjYXQ3U09VenREQkZKSVJvTzg4SFBjR2ZFaG9JWEQ4NjFlNERoVW4tbFZ0RVBmSXhJS2FEZTE5NDRZTE9SYXZRMWtvLUNMZTBQX2JvUkgwQzJYZDBmaGktenVVZllZWmVkMUxqQlR0ZlY3YU9tYUdFdkVyYVN6MXdha0hweW5yNkZrMHphb1NUbGk3Smt0a3lISl84eUIyaFZaS0RHNkRkdjk1UGZqMGtxMHg3Vkl2WDFoV2l3RE9jLUxlTlo3aUd6Rjl6c3FHZldreUFGUWRqdkRGRHNXWjlhaTExX1VQcVp1cUZjcF8yZ0ZnRk12WQ==","email":"oluwafemi.osinowo@outlook.com"},"registry.redhat.io":{"auth":"NTIzOTYwODd8dWhjLTFJR1BxOTNCNTBpWmI2MFpKMEM2cnhBcEZTeDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSTFNVFk1TW1VMU1UUXhOMkkwTTJZME9XRXlOVE01WkRCaU5EQTFNRFkxTmlKOS5maGU1OXFaVjlTZmI0Q2kxQkRReG12U25WQzBpZC05YlJLSlV2UUpaczR0d0NkbEZuZng1c2ZRaFdkVDgzMnVsQmlWNFlqekJNM2J5MlBfM041M1hTTXhxS3FZQkNuakNWck9OZjhjSWdkTXh2V25oTVV5SzdrZVkwcU5iM3h1aU9YUjVvV3FjeWVoeVgwRzBqdUlya01NUTRTcnVtcHVkdmxockE1eWtvMzNfRzlpaU9YQklzVmY5TmxLb1NyRDNMOFZkNlByTHQxNFRGX3Y5bHJDWEs5NV9sY3dqNV9jVWpTaEFILTdoLXJvOG1kNlptWVBtMlVxeDFkNFNfN3hJWDItaUtXeUl6ZEJjN196OXVEUlRPRGFiLVgyOG81YmYtcjdfazFxOHk2eHE1dWhQV0tRbGFRakhyVU5tYll0LTFydzVNbFM5X3NBZ2YxMjk5YTFPZVlsWTFKVG1wdHhma0hjc2prdGUyZDRiQWdPeGhiYVpfRklIY1h6SjNndHpZOEpnYXFncnkyU2JsWUFRNHF3bkNYanlkYThDa2J0WC1YRzZILVdUUGo2SUJmZEhpbjRON1RqT0FrVEtjYXQ3U09VenREQkZKSVJvTzg4SFBjR2ZFaG9JWEQ4NjFlNERoVW4tbFZ0RVBmSXhJS2FEZTE5NDRZTE9SYXZRMWtvLUNMZTBQX2JvUkgwQzJYZDBmaGktenVVZllZWmVkMUxqQlR0ZlY3YU9tYUdFdkVyYVN6MXdha0hweW5yNkZrMHphb1NUbGk3Smt0a3lISl84eUIyaFZaS0RHNkRkdjk1UGZqMGtxMHg3Vkl2WDFoV2l3RE9jLUxlTlo3aUd6Rjl6c3FHZldreUFGUWRqdkRGRHNXWjlhaTExX1VQcVp1cUZjcF8yZ0ZnRk12WQ==","email":"oluwafemi.osinowo@outlook.com"}}}'
