- name: Compute virtual machine names
  set_fact:
    virtual_machine_names: >
      {{ virtual_machine_names | default ({}) | combine({ item.hostname: item.hostname + "." + openshift_install_config.dns_host_domain }) }}
  with_items: '{{ openshift_cluster_hosts }}'
