- name: Create ISO image directory structure
  file:
    path: '{{ helper.images_dir }}/{{ virtual_machine_names[item.hostname] }}-isoroot/boot/grub'
    state: directory

- name: Copy the GRUB configuration to ISO
  template:
    src: files/boot/grub/grub.cfg
    dest: '{{ helper.images_dir }}/{{ virtual_machine_names[item.hostname] }}-isoroot/boot/grub/grub.cfg'

- import_tasks: define_boot_iso_name.yml

- name: Generate the ISO image
  command: grub2-mkrescue --output {{ boot_iso_filename }} {{ helper.images_dir }}/{{ virtual_machine_names[item.hostname] }}-isoroot

- name: Obtain ISO image info
  stat:
    path: '{{ boot_iso_filename }}'
  register: boot_iso_info
