- name: Ensure libvirt client libraries are installed
  yum:
    name:
      - libvirt-client
      - '{{ rpm_name["libvirt-python"] }}'
    state: present
  become: True

- name: Read CoreOS stream
  import_role:
    name: openshift_common
    tasks_from: read_coreos_stream.yml

- name: Download the CoreOS image
  import_role:
    name: openshift_common
    tasks_from: download_coreos.yml
  vars:
    download_coreos_url: '{{ coreos.qemu_qcow2_url }}'
    download_coreos_checksum: '{{ coreos.qemu_qcow2_checksum }}'

- name: Set image filename
  set_fact:
    libvirt_image_filename: '{{ download_coreos_image_filename }}'
