- name: Generate ignition configs
  import_role:
    name: openshift_common
    tasks_from: generate_ignition.yml

- name: Ensure prerequisites
  import_tasks: ensure_prereqs.yml

- name: Deploy template
  import_tasks: deploy_template.yml

- name: Deploy hosts
  import_tasks: deploy_hosts.yml

- name: Wait for ssh on OpenShift hosts
  import_role:
    name: openshift_common
    tasks_from: wait_for_ssh.yml
  vars:
    wait_for_ssh_existing_vms: '{{ libvirt_existing_vms }}'

- name: Wait for the bootstrap to complete
  import_role:
    name: openshift_common
    tasks_from: wait_for_bootstrap.yml

- name: Stop bootstrap virtual machine
  import_role:
    name: openshift_libvirt_common
    tasks_from: stop_bootstrap_vm.yml

- name: Wait for the installation to complete
  import_role:
    name: openshift_common
    tasks_from: wait_for_install.yml
